modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv3"
[[mods]]
modId = "yggdrasil"
version = "${file.jarVersion}"
displayName = "Yggdrasil"
#logoFile="logo.png"
authors = "DavidQF555"
description = 'This mod adds new features'
[[dependencies.yggdrasil]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.yggdrasil]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
