modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPLv3"
[[mods]]
modId = "yggdrasil"
version = "${file.jarVersion}"
displayName = "Yggdrasil"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds new features'
[[dependencies.yggdrasil]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.yggdrasil]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
